# yaml-language-server: $schema=https://www.schemastore.org/github-action
name: Titanoboa LiveCD ISO builder
description: >-
  Create LiveCDs of a bootc container image.
  The resulting iso will be placed at `output.iso`.
inputs:
  image-ref:
    description: Reference to the bootc container image to build the ISO from.
    required: true
  iso-dest:
    description: Where the iso will be placed
    required: false
    default: ${{ github.workspace }}/output.iso
outputs:
  iso-dest:
    description: Where the iso was be placed
    value: ${{ steps.generate-iso.outputs.iso_dest }}

runs:
  using: composite
  steps:
    - name: Generate iso
      id: generate-iso
      env:
        DESTINATION_PATH: ${{ inputs.iso-dest }}
        TITANOBOA_CTR_IMAGE: ${{ inputs.image-ref }}
        BUILDER_IMGREF: "ghcr.io/${{ github.action_repository || github.repository }}:latest"
      shell: bash
      run: |
        set -euxo pipefail
        cd "$GITHUB_ACTION_PATH" || exit 1

        # Pull/build builder image
        if ! sudo podman image exists "$BUILDER_IMGREF"; then
            sudo podman pull "$BUILDER_IMGREF"
        fi

        # Build ISO
        mkdir -p ./output
        rm -rf ./output/*
        sudo podman run \
          --rm -it \
          --security-opt label=disable \
          -v ./output:/output \
          --mount type=image,source="$TITANOBOA_CTR_IMAGE",dst=/rootfs \
          "$BUILDER_IMGREF"
        ISO_FILENAME="$(realpath ./output/*.iso)"

        # Fix iso file permisions
        sudo chown $(id -u):$(id -g) "$ISO_FILENAME"

        # Move iso to iso-dest
        dest="$(realpath --relative-base="${GITHUB_WORKSPACE}" "${DESTINATION_PATH}")"
        dest="$(realpath -m $dest)"
        mkdir -p "$(dirname "$dest")"
        mv "$ISO_FILENAME" "$dest"
        echo "iso_dest=$dest" >> "$GITHUB_OUTPUT"

    - name: Check the iso is there
      shell: bash
      env:
        DEST_ISO: ${{ steps.generate-iso.outputs.iso_dest }}
      run: |
        [[ -f "${DEST_ISO}" ]] || {
          echo "::error:Iso file does not exist at ${DEST_ISO}"
          exit 1
        }
