name: Titanoboa LiveCD ISO builder
description: >-
  Create LiveCDs of a bootc container image.
  The resulting iso will be placed at `output.iso`.
inputs:
  image-ref:
    description: Reference to the bootc container image.
    required: true
  livesys:
    description: Install livesys helpers on the rootfs for the ISO
    required: false
    default: "false"
  compression:
    description: Which type of compression will the ISO will use (erofs (default), or squashfs (smaller sizes, slower read))
    required: false
    default: squashfs
  hook-post-rootfs:
    description: >-
      Hook ran in the rootfs of the container image before
      being squashed in `squashfs.img`.
  iso-dest:
    description: Where the iso will be placed
    required: false
    default: ${{ github.workspace }}/output.iso
  flatpaks-list:
    description: Path to a file with a newline separated flatpak apps list to be installed in the rootfs.
    required: false
    default: none
outputs:
  iso-dest:
    description: Where the iso was be placed
    value: ${{ steps.generate-iso.outputs.iso_dest }}

runs:
  using: composite
  steps:
    - name: Install Just
      id: install-just
      uses: extractions/setup-just@v3

    - name: Generate iso
      id: generate-iso
      env:
        WORKSPACE: ${{ github.workspace }}
        DESTINATION_PATH: ${{ inputs.iso-dest }}
        COMPRESSION: ${{ inputs.compression }}
        IMAGE_REF: ${{ inputs.image-ref }}
        LIVESYS: ${{ inputs.livesys }}
        ACTION_PATH: ${{ github.action_path }}
        FLATPAKS_LIST: ${{ inputs.flatpaks-list }}
      shell: bash
      run: |
        set -euxo pipefail
        cd "${ACTION_PATH}"

        just=$(which just)

        USE_LIVESYS=$(echo "${LIVESYS}" | sed -e 's/true/1/g' -e 's/false/0/g')

        # File descriptors used:
        # - 3: hook-post-rootfs
        sudo PATH="$PATH" $just build "${IMAGE_REF}" 1 "${USE_LIVESYS}" "${FLATPAKS_LIST}" "${COMPRESSION}" \
          3< <(cat - <<-HOOKPOSTROOTFS
        ${{ inputs.hook-post-rootfs }}
        HOOKPOSTROOTFS)
        
        # Fix iso file permisions
        sudo chown $(id -u):$(id -g) ./output.iso

        # Move iso to iso-dest
        dest="$(realpath --relative-base="${WORKSPACE}" "${DESTINATION_PATH}")"
        dest="$(realpath $dest)"
        if [[ "$(realpath ./output.iso)" != "${dest}" ]]; then
          mkdir -p "$(dirname "$dest")"
          mv ./output.iso "$dest"
        fi
        echo "iso_dest=$dest" >> "$GITHUB_OUTPUT"
        
    - name: Cleanup
      id: titanoboa-cleanup
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        cd "${ACTION_PATH}"
        # Cleanup
        sudo PATH="$PATH" $(which just) clean
        
    - name: Check the iso is there
      shell: bash
      env:
        DEST_ISO: ${{ steps.generate-iso.outputs.iso_dest }}
      run: |
        [[ -f "${DEST_ISO}" ]] || {
          echo "::error:Iso file does not exist at $dest"
          exit 1
        }
