# run with --cap-add sys_admin --security-opt label=disable --squash

FROM ghcr.io/zirconium-dev/zirconium:latest
COPY ./src /src
RUN --mount=type=cache,target=/var/tmp/libdnf5,id=libdnf5 \
    /src/build.sh
RUN rm -fr /src
